spring.application.name=PortableMessengerApp
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6965/postgres
spring.datasource.username=postgres
spring.datasource.password=asoradium
server.port=8080
server.servlet.session.timeout=300
spring.session.redis.flush-mode=on_save
spring.session.redis.namespace=spring:session
spring.data.redis.host=localhost
spring.data.redis.username=
spring.data.redis.password=
spring.data.redis.port=6379
spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000
trace=true
spring.jpa.generate-ddl=true